# Generated by Django 4.2.7 on 2024-02-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.product'),
        ),
    ]
