# Generated by Django 4.2.7 on 2024-03-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_AED',
        ),
    ]
