# Generated by Django 4.2.7 on 2024-03-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_price_product_price_aed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
    ]
